/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface ActivityLog {
  actor_agent_id: string | null;
  actor_label: string | null;
  actor_type: string;
  actor_user_id: string | null;
  changes: string | null;
  created_at: string;
  entity_id: string;
  entity_type: string;
  id: string;
  scope_id: string | null;
  source: string;
  verb: string;
}

export interface AiAgents {
  actor_user_id: string;
  can_create_tasks: Generated<number>;
  created_at: string;
  enabled: Generated<number>;
  id: string;
  name: string;
  on_behalf_of_user_id: string;
  updated_at: string;
  version: Generated<number>;
}

export interface ApiTokens {
  ai_agent_id: string | null;
  capabilities: string;
  created_at: string;
  expires_at: string | null;
  id: string;
  last_used_at: string | null;
  name: string;
  revoked_at: string | null;
  scope_ids: string | null;
  token_hash: string;
  token_prefix: string;
  user_id: string;
}

export interface Attachments {
  created_at: string;
  deleted_at: string | null;
  event_id: string | null;
  external_url: string | null;
  filename: string;
  id: string;
  is_ai_context: Generated<number>;
  mime_type: string;
  scope_id: string | null;
  size_bytes: number;
  source: Generated<string>;
  storage_path: string | null;
  task_id: string | null;
  updated_at: string;
  uploaded_by: string | null;
  version: Generated<number>;
}

export interface Calendars {
  color: string | null;
  created_at: string;
  deleted_at: string | null;
  id: string;
  inbox_visible: number | null;
  kind: string;
  last_error: string | null;
  last_error_at: string | null;
  last_refreshed_at: string | null;
  name: string;
  origin: Generated<string>;
  project_id: string | null;
  refresh_interval: number | null;
  scope_id: string;
  shared_with_scope: Generated<number>;
  source_kind: string | null;
  source_secret_enc: string | null;
  source_url: string | null;
  source_username: string | null;
  strip_alarms: Generated<number>;
  sync_seq: Generated<number>;
  updated_at: string;
  version: Generated<number>;
  writable: Generated<number>;
}

export interface ChangeLog {
  created_at: string;
  entity_id: string;
  entity_type: string;
  operation: string;
  scope_id: string | null;
  seq: Generated<number | null>;
}

export interface ChecklistItems {
  checklist_id: string;
  created_at: string;
  deleted_at: string | null;
  done: Generated<number>;
  done_at: string | null;
  done_by: string | null;
  id: string;
  position: string;
  text: string;
  updated_at: string;
  version: Generated<number>;
}

export interface Checklists {
  created_at: string;
  deleted_at: string | null;
  id: string;
  name: string;
  pinned: Generated<number>;
  pinned_by: string | null;
  position: string;
  show_completed_inline: Generated<number>;
  subtask_id: string | null;
  task_id: string;
  updated_at: string;
  version: Generated<number>;
}

export interface Comments {
  author_id: string | null;
  body: string;
  created_at: string;
  deleted_at: string | null;
  guest_name: string | null;
  id: string;
  share_id: string | null;
  task_id: string;
  updated_at: string;
  version: Generated<number>;
}

export interface EventAttendees {
  email: string | null;
  event_id: string;
  id: string;
  name: string | null;
  partstat: Generated<string | null>;
  role: Generated<string | null>;
  user_id: string | null;
}

export interface EventInboxMarks {
  calendar_id: string;
  created_at: string;
  deleted_at: string | null;
  id: string;
  recurrence_id: string | null;
  uid: string;
  updated_at: string;
  user_id: string;
  version: Generated<number>;
  visible: number;
}

export interface EventOccurrences {
  ends_at: string;
  event_id: string;
  starts_at: string;
}

export interface Events {
  all_day: Generated<number>;
  calendar_id: string;
  classification: Generated<string | null>;
  created_at: string;
  deleted_at: string | null;
  description: string | null;
  duration: string | null;
  ends_at: string | null;
  etag: string | null;
  exdate: string | null;
  id: string;
  is_orphan_override: Generated<number>;
  location: string | null;
  organizer: string | null;
  raw_ical: string | null;
  rdate: string | null;
  recurrence_id: string | null;
  rrule: string | null;
  sequence: Generated<number>;
  starts_at: string;
  status: Generated<string | null>;
  summary: string;
  timezone: string | null;
  transparency: Generated<string | null>;
  uid: string;
  updated_at: string;
  version: Generated<number>;
}

export interface Grants {
  capabilities: string | null;
  created_at: string;
  expires_at: string | null;
  first_used_at: string | null;
  id: string;
  issuer_user_id: string | null;
  kind: string;
  last_used_at: string | null;
  max_uses: Generated<number>;
  payload: string | null;
  revoked_at: string | null;
  role: string | null;
  secret_version: Generated<number>;
  subject_id: string | null;
  subject_type: string;
  token_hmac: string;
  use_count: Generated<number>;
}

export interface InstanceLinks {
  base_url: string;
  created_at: string;
  created_by: string | null;
  cursor: string | null;
  id: string | null;
  last_error: string | null;
  last_error_at: string | null;
  last_sync_at: string | null;
  local_seq: Generated<number>;
  name: string | null;
  remote_scope_id: string | null;
  scope_id: string;
  token_enc: string;
  updated_at: string;
}

export interface InstanceSettings {
  created_at: string;
  key: string;
  updated_at: string;
  value: string;
}

export interface Labels {
  color: string;
  created_at: string;
  deleted_at: string | null;
  id: string;
  name: string;
  scope_id: string;
}

export interface MailAccounts {
  consecutive_errors: Generated<number>;
  created_at: string;
  deleted_at: string | null;
  enabled: Generated<number>;
  host: string;
  id: string;
  last_error: string | null;
  last_error_at: string | null;
  last_polled_at: string | null;
  name: string;
  poll_interval: number | null;
  port: Generated<number>;
  secret_enc: string | null;
  security: Generated<string>;
  updated_at: string;
  user_id: string;
  username: string;
  version: Generated<number>;
}

export interface MailMessages {
  account_id: string;
  body_text: string | null;
  created_at: string;
  deleted_at: string | null;
  disposition: Generated<string>;
  error: string | null;
  folder: string;
  from_address: string | null;
  from_name: string | null;
  has_html: Generated<number>;
  id: string;
  in_reply_to: string | null;
  internal_date: string | null;
  message_id: string | null;
  message_key: string;
  raw_bytes: Generated<number>;
  raw_path: string | null;
  reference_ids: string | null;
  rule_id: string | null;
  sent_at: string | null;
  subject: string | null;
  task_id: string | null;
  thread_id: string;
  to_addresses: string | null;
  uid: string;
  uid_validity: string;
  updated_at: string;
  version: Generated<number>;
}

export interface MailRules {
  account_id: string;
  action: string;
  attachments_to_task: Generated<number>;
  body_to_description: Generated<number>;
  created_at: string;
  deleted_at: string | null;
  enabled: Generated<number>;
  folder: string;
  id: string;
  inbox_visible: Generated<number>;
  last_error: string | null;
  last_error_at: string | null;
  last_seen_at: string | null;
  last_uid: string | null;
  position: string;
  project_id: string | null;
  scope_id: string;
  title_template: Generated<string>;
  uid_validity: string | null;
  updated_at: string;
  version: Generated<number>;
}

export interface MailThreads {
  account_id: string;
  created_at: string;
  deleted_at: string | null;
  first_at: string | null;
  id: string;
  last_at: string | null;
  message_count: Generated<number>;
  subject: string | null;
  task_id: string | null;
  thread_key: string;
  updated_at: string;
  version: Generated<number>;
}

export interface Projects {
  ai_description: string | null;
  ai_instructions: string | null;
  archived_at: string | null;
  created_at: string;
  deleted_at: string | null;
  id: string;
  name: string;
  position: string;
  scope_id: string;
  updated_at: string;
  version: Generated<number>;
}

export interface PushSubscriptions {
  auth: string;
  created_at: string;
  endpoint: string;
  fail_count: Generated<number>;
  id: string;
  last_ok_at: string | null;
  p256dh: string;
  platform: string;
  user_agent: string | null;
  user_id: string;
}

export interface Reminders {
  channel: string;
  created_at: string;
  event_id: string | null;
  fired_at: string | null;
  id: string;
  task_id: string | null;
  trigger: string;
  user_id: string;
}

export interface SchemaMigrations {
  applied_at: string;
  name: string | null;
}

export interface ScopeAccessRevocations {
  id: string;
  revoked_at: string;
  scope_id: string;
  user_id: string;
}

export interface ScopeMembers {
  created_at: string;
  external_calendar_id: string | null;
  id: string;
  role: Generated<string>;
  scope_id: string;
  user_id: string | null;
}

export interface Scopes {
  ai_description: string | null;
  ai_instructions: string | null;
  color: string;
  created_at: string;
  deleted_at: string | null;
  icon: string | null;
  id: string;
  kind: Generated<string>;
  name: string;
  owner_id: string;
  position: string;
  updated_at: string;
  version: Generated<number>;
}

export interface Sessions {
  created_at: string;
  expires_at: string;
  id: string;
  last_used_at: string;
  refresh_hash: string;
  revoked_at: string | null;
  user_agent: string | null;
  user_id: string;
}

export interface ShareAccesses {
  first_seen: string;
  guest_name: string | null;
  guest_ref: string;
  id: string;
  last_seen: string;
  share_id: string;
}

export interface Shares {
  checklist_id: string | null;
  created_at: string;
  created_by: string;
  expires_at: string | null;
  failed_attempts: Generated<number>;
  id: string;
  locked_until: string | null;
  max_views: number | null;
  password_hash: string | null;
  permission: Generated<string>;
  require_name: Generated<number>;
  revoked_at: string | null;
  secret_version: Generated<number>;
  task_id: string | null;
  token_hmac: string;
  view_count: Generated<number>;
}

export interface Subtasks {
  created_at: string;
  deleted_at: string | null;
  done: Generated<number>;
  id: string;
  position: string;
  task_id: string;
  title: string;
  updated_at: string;
  version: Generated<number>;
}

export interface SyncOpIds {
  created_at: string;
  op_id: string;
  principal_key: string;
  result: string;
}

export interface TaskAssignees {
  assigned_at: string;
  task_id: string;
  user_id: string;
}

export interface TaskLabels {
  label_id: string;
  task_id: string;
}

export interface TaskLeases {
  acquired_at: string;
  agent_id: string | null;
  expires_at: string;
  task_id: string;
  user_id: string;
}

export interface Tasks {
  ai_instructions: string | null;
  ai_mode: Generated<string>;
  caldav_etag: string | null;
  caldav_uid: string | null;
  calendar_id: string | null;
  completed_at: string | null;
  created_at: string;
  created_by: string;
  deadline: string | null;
  delegate_agent_id: string | null;
  deleted_at: string | null;
  description: string | null;
  due_date: string | null;
  due_time: string | null;
  event_calendar_id: string | null;
  event_recurrence_id: string | null;
  event_uid: string | null;
  id: string;
  mail_account_id: string | null;
  mail_message_key: string | null;
  mail_thread_key: string | null;
  origin: Generated<string>;
  position: string;
  project_id: string | null;
  recurrence_mode: Generated<string | null>;
  recurrence_parent_id: string | null;
  rrule: string | null;
  scope_id: string;
  search_text: string | null;
  source_kind: string | null;
  status: Generated<string>;
  title: string;
  updated_at: string;
  version: Generated<number>;
  view_mode: Generated<string>;
}

export interface UserInvites {
  created_at: string;
  created_by: string;
  expires_at: string;
  id: string;
  token_hmac: string;
  used_at: string | null;
  user_id: string;
}

export interface Users {
  accent: Generated<string>;
  avatar_color: string | null;
  created_at: string;
  deleted_at: string | null;
  email: string | null;
  id: string;
  instance_link_id: string | null;
  kind: Generated<string>;
  locale: Generated<string>;
  name: string;
  password_hash: string | null;
  remote_user_id: string | null;
  role: Generated<string>;
  theme: Generated<string>;
  timezone: Generated<string>;
  updated_at: string;
  version: Generated<number>;
}

export interface UserSettings {
  collapsed_groups: string | null;
  daily_digest_at: string | null;
  done_cleared_at: string | null;
  event_task_deleted: Generated<string>;
  gravatar: Generated<number>;
  hidden_calendar_ids: string | null;
  inbox_origin: Generated<string>;
  inbox_position: Generated<string>;
  inbox_show_overdue: Generated<number>;
  notify_prefs: Generated<string>;
  quiet_hours_end: string | null;
  quiet_hours_start: string | null;
  show_calendar_widget: Generated<number>;
  show_overdue_section: Generated<number>;
  updated_at: string;
  user_id: string;
  week_start: Generated<string>;
}

export interface Webhooks {
  created_at: string;
  disabled_at: string | null;
  enabled: Generated<number>;
  events: string;
  fail_count: Generated<number>;
  id: string;
  last_error: string | null;
  last_success_at: string | null;
  scope_ids: string | null;
  secret_enc: string;
  updated_at: string;
  url: string;
  user_id: string;
}

export interface DB {
  activity_log: ActivityLog;
  ai_agents: AiAgents;
  api_tokens: ApiTokens;
  attachments: Attachments;
  calendars: Calendars;
  change_log: ChangeLog;
  checklist_items: ChecklistItems;
  checklists: Checklists;
  comments: Comments;
  event_attendees: EventAttendees;
  event_inbox_marks: EventInboxMarks;
  event_occurrences: EventOccurrences;
  events: Events;
  grants: Grants;
  instance_links: InstanceLinks;
  instance_settings: InstanceSettings;
  labels: Labels;
  mail_accounts: MailAccounts;
  mail_messages: MailMessages;
  mail_rules: MailRules;
  mail_threads: MailThreads;
  projects: Projects;
  push_subscriptions: PushSubscriptions;
  reminders: Reminders;
  schema_migrations: SchemaMigrations;
  scope_access_revocations: ScopeAccessRevocations;
  scope_members: ScopeMembers;
  scopes: Scopes;
  sessions: Sessions;
  share_accesses: ShareAccesses;
  shares: Shares;
  subtasks: Subtasks;
  sync_op_ids: SyncOpIds;
  task_assignees: TaskAssignees;
  task_labels: TaskLabels;
  task_leases: TaskLeases;
  tasks: Tasks;
  user_invites: UserInvites;
  user_settings: UserSettings;
  users: Users;
  webhooks: Webhooks;
}
