/*
 * GENERAT · no l'editis a mà.
 *
 * Surt de `packages/design-system/plou/tokens` i de `femho/tokens.css` amb
 * `node tools/gen/tokens-compose.mjs`. D7: **una direcció i prou.** El CSS és la font
 * de veritat; qualsevol canvi fet aquí desapareix a la propera generació.
 *
 * Els gradients no hi són: a Compose són `Brush` i no `Color` (veure `Brand.kt`).
 */
@file:Suppress("MagicNumber", "LongMethod")

package ho.fem.designsystem

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
data class FemhoColors(
    val cardBg: Color,
    val cardBorder: Color,
    val codeBg: Color,
    val columnBg: Color,
    val dangerBg: Color,
    val dangerText: Color,
    val dayHoverRing: Color,
    val dialogBackdrop: Color,
    val dialogBg: Color,
    val divider: Color,
    val dividerSoft: Color,
    val dot1: Color,
    val dot2: Color,
    val dot3: Color,
    val fabBg: Color,
    val fabText: Color,
    val femhoScope1: Color,
    val femhoScope2: Color,
    val femhoScope3: Color,
    val femhoScope4: Color,
    val femhoScope5: Color,
    val femhoScope6: Color,
    val femhoScope7: Color,
    val femhoScope8: Color,
    val ghostBg: Color,
    val ghostText: Color,
    val glassBg: Color,
    val glassBgStrong: Color,
    val glassBorder: Color,
    val glassFill: Color,
    val glassSheetBg: Color,
    val glassText: Color,
    val glassTextFaint: Color,
    val glassTextSoft: Color,
    val inboxPillBg: Color,
    val ink: Color,
    val inkFaint: Color,
    val inkSoft: Color,
    val inputBg: Color,
    val inputBorder: Color,
    val kicker: Color,
    val navIdle: Color,
    val onBrand: Color,
    val panelBg: Color,
    val plouBlue: Color,
    val plouBlueInk: Color,
    val plouOrange: Color,
    val plouOrangeInk: Color,
    val plouPink: Color,
    val plouPinkInk: Color,
    val rangeTrack: Color,
    val ringRadar: Color,
    val scrim: Color,
    val segBg: Color,
    val segText: Color,
    val sidebarBg: Color,
    val switcherBg: Color,
    val switcherBorder: Color,
    val tagBg: Color,
    val tagText: Color,
    val trackOff: Color,
)

/** Els accents de Plou. Canvien els colors de marca, no la resta de l'esquema. */
enum class FemhoAccent { DEFAULT, MONOCOOL, MONOWARM, SOFT }

internal val lightColors = FemhoColors(
        cardBg = Color(0xFFFFFFFF),
        cardBorder = Color(0x1214161E),
        codeBg = Color(0x0D14161E),
        columnBg = Color(0x0514161E),
        dangerBg = Color(0x1AE64646),
        dangerText = Color(0xFFC94040),
        dayHoverRing = Color(0x4714161E),
        dialogBackdrop = Color(0x7314141E),
        dialogBg = Color(0xFFFFFFFF),
        divider = Color(0x1414161E),
        dividerSoft = Color(0x0F14161E),
        dot1 = Color(0xFF6EA8FF),
        dot2 = Color(0xFFFF9D4D),
        dot3 = Color(0xFFFF6FA0),
        fabBg = Color(0x0F14161E),
        fabText = Color(0xFF14151A),
        femhoScope1 = Color(0xFF4FB3A3),
        femhoScope2 = Color(0xFF8B7BD8),
        femhoScope3 = Color(0xFFD99A3F),
        femhoScope4 = Color(0xFF5C93C4),
        femhoScope5 = Color(0xFFC96F8F),
        femhoScope6 = Color(0xFF6AA84F),
        femhoScope7 = Color(0xFFB5763F),
        femhoScope8 = Color(0xFF7A8FA6),
        ghostBg = Color(0x0F14161E),
        ghostText = Color(0xFF14151A),
        glassBg = Color(0x8014141A),
        glassBgStrong = Color(0x8C14141A),
        glassBorder = Color(0x26FFFFFF),
        glassFill = Color(0x29FFFFFF),
        glassSheetBg = Color(0xEBFFFFFF),
        glassText = Color(0xFFFFFFFF),
        glassTextFaint = Color(0x99FFFFFF),
        glassTextSoft = Color(0xB3FFFFFF),
        inboxPillBg = Color(0x80FFFFFF),
        ink = Color(0xFF14151A),
        inkFaint = Color(0x6B14161E),
        inkSoft = Color(0x8C14161E),
        inputBg = Color(0x0D14161E),
        inputBorder = Color(0x1A14161E),
        kicker = Color(0xFFE0793A),
        navIdle = Color(0x8C14161E),
        onBrand = Color(0xFFFFFFFF),
        panelBg = Color(0xFFFFFFFF),
        plouBlue = Color(0xFF6EA8FF),
        plouBlueInk = Color(0xFF3B6FD6),
        plouOrange = Color(0xFFFF9D4D),
        plouOrangeInk = Color(0xFFE0793A),
        plouPink = Color(0xFFFF6FA0),
        plouPinkInk = Color(0xFFD6598A),
        rangeTrack = Color(0x1F14161E),
        ringRadar = Color(0x99FF9F7A),
        scrim = Color(0x5914151A),
        segBg = Color(0x0D14161E),
        segText = Color(0x8C14161E),
        sidebarBg = Color(0xB3FFFFFF),
        switcherBg = Color(0xD9FFFFFF),
        switcherBorder = Color(0x0F14161E),
        tagBg = Color(0x0F14161E),
        tagText = Color(0xFF3A3D46),
        trackOff = Color(0x1F14161E),
)

internal val darkColors = FemhoColors(
        cardBg = Color(0x0FFFFFFF),
        cardBorder = Color(0x17FFFFFF),
        codeBg = Color(0x0FFFFFFF),
        columnBg = Color(0x08FFFFFF),
        dangerBg = Color(0x1AE64646),
        dangerText = Color(0xFFC94040),
        dayHoverRing = Color(0x52FFFFFF),
        dialogBackdrop = Color(0x8C000000),
        dialogBg = Color(0xFF171922),
        divider = Color(0x17FFFFFF),
        dividerSoft = Color(0x12FFFFFF),
        dot1 = Color(0xFF6EA8FF),
        dot2 = Color(0xFFFF9D4D),
        dot3 = Color(0xFFFF6FA0),
        fabBg = Color(0x14FFFFFF),
        fabText = Color(0xFFFFFFFF),
        femhoScope1 = Color(0xFF62C9B8),
        femhoScope2 = Color(0xFFA396E8),
        femhoScope3 = Color(0xFFE8B05A),
        femhoScope4 = Color(0xFF7AABD8),
        femhoScope5 = Color(0xFFDC8AA8),
        femhoScope6 = Color(0xFF85C268),
        femhoScope7 = Color(0xFFCC8F58),
        femhoScope8 = Color(0xFF9AADC2),
        ghostBg = Color(0x14FFFFFF),
        ghostText = Color(0xFFFFFFFF),
        glassBg = Color(0x8014141A),
        glassBgStrong = Color(0x8C14141A),
        glassBorder = Color(0x26FFFFFF),
        glassFill = Color(0x29FFFFFF),
        glassSheetBg = Color(0xEBFFFFFF),
        glassText = Color(0xFFFFFFFF),
        glassTextFaint = Color(0x99FFFFFF),
        glassTextSoft = Color(0xB3FFFFFF),
        inboxPillBg = Color(0x1FFFFFFF),
        ink = Color(0xFFF5F6FA),
        inkFaint = Color(0x73F5F6FA),
        inkSoft = Color(0x9EF5F6FA),
        inputBg = Color(0x0FFFFFFF),
        inputBorder = Color(0x1FFFFFFF),
        kicker = Color(0xFFFF9D4D),
        navIdle = Color(0x8CF5F6FA),
        onBrand = Color(0xFFFFFFFF),
        panelBg = Color(0xFF12131A),
        plouBlue = Color(0xFF6EA8FF),
        plouBlueInk = Color(0xFF3B6FD6),
        plouOrange = Color(0xFFFF9D4D),
        plouOrangeInk = Color(0xFFE0793A),
        plouPink = Color(0xFFFF6FA0),
        plouPinkInk = Color(0xFFD6598A),
        rangeTrack = Color(0x29FFFFFF),
        ringRadar = Color(0x99FF9F7A),
        scrim = Color(0x8C000000),
        segBg = Color(0x0FFFFFFF),
        segText = Color(0x8CFFFFFF),
        sidebarBg = Color(0xB312121A),
        switcherBg = Color(0xBF14141A),
        switcherBorder = Color(0x14FFFFFF),
        tagBg = Color(0x14FFFFFF),
        tagText = Color(0xCCFFFFFF),
        trackOff = Color(0x26FFFFFF),
)

@Immutable
data class FemhoGradientStops(
    val appBg: List<Color>,
    val gradientAlert: List<Color>,
    val gradientBrand: List<Color>,
    val gradientBrand2stop: List<Color>,
    val gradientBrandAlt: List<Color>,
    val gradientBrandText: List<Color>,
    val gradientRadar: List<Color>,
    val gradientToggle: List<Color>,
    val gradientWashCool: List<Color>,
    val gradientWashTag: List<Color>,
    val gradientWashWarm: List<Color>,
    val outerBg: List<Color>,
    val pageBg: List<Color>,
)

internal val lightGradients = FemhoGradientStops(
        appBg = listOf(Color(0xFFF8F9FD), Color(0xFFFBF6F4), Color(0xFFFDF3F6)),
        gradientAlert = listOf(Color(0xFF1A2A5C), Color(0xFF7A3A8C), Color(0xFFFF6F4D), Color(0xFFFF9D4D)),
        gradientBrand = listOf(Color(0xFF6EA8FF), Color(0xFFFF9D4D), Color(0xFFFF6FA0)),
        gradientBrand2stop = listOf(Color(0xFF6EA8FF), Color(0xFFFF9D4D)),
        gradientBrandAlt = listOf(Color(0xFF6EA8FF), Color(0xFFFF9D4D), Color(0xFFFF6FA0)),
        gradientBrandText = listOf(Color(0xFF3B6FD6), Color(0xFFE0793A), Color(0xFFD6598A)),
        gradientRadar = listOf(Color(0xFF111726), Color(0xFF1C1A2C), Color(0xFF241A24)),
        gradientToggle = listOf(Color(0xFF6EA8FF), Color(0xFFFF6FA0)),
        gradientWashCool = listOf(Color(0x1F6EA8FF), Color(0x1AFF6FA0)),
        gradientWashTag = listOf(Color(0x336EA8FF), Color(0x33FF6FA0)),
        gradientWashWarm = listOf(Color(0x29FF9D4D), Color(0x1AFF6FA0)),
        outerBg = listOf(Color(0xFFEEF3FF), Color(0xFFFDF3EE), Color(0xFFFDEEF4)),
        pageBg = listOf(Color(0xFFEEF3FF), Color(0xFFFDF3EE), Color(0xFFFDEEF4)),
)

internal val darkGradients = FemhoGradientStops(
        appBg = listOf(Color(0xFF0E0F16), Color(0xFF181420), Color(0xFF1C1420)),
        gradientAlert = listOf(Color(0xFF1A2A5C), Color(0xFF7A3A8C), Color(0xFFFF6F4D), Color(0xFFFF9D4D)),
        gradientBrand = listOf(Color(0xFF6EA8FF), Color(0xFFFF9D4D), Color(0xFFFF6FA0)),
        gradientBrand2stop = listOf(Color(0xFF6EA8FF), Color(0xFFFF9D4D)),
        gradientBrandAlt = listOf(Color(0xFF6EA8FF), Color(0xFFFF9D4D), Color(0xFFFF6FA0)),
        gradientBrandText = listOf(Color(0xFF3B6FD6), Color(0xFFE0793A), Color(0xFFD6598A)),
        gradientRadar = listOf(Color(0xFF111726), Color(0xFF1C1A2C), Color(0xFF241A24)),
        gradientToggle = listOf(Color(0xFF6EA8FF), Color(0xFFFF6FA0)),
        gradientWashCool = listOf(Color(0x1F6EA8FF), Color(0x1AFF6FA0)),
        gradientWashTag = listOf(Color(0x336EA8FF), Color(0x33FF6FA0)),
        gradientWashWarm = listOf(Color(0x29FF9D4D), Color(0x1AFF6FA0)),
        outerBg = listOf(Color(0xFF141826), Color(0xFF05060A)),
        pageBg = listOf(Color(0xFF141826), Color(0xFF05060A)),
)

/** Els colors que cada accent sobreescriu, aplicats damunt de l'esquema del tema. */
internal fun applyAccent(base: FemhoColors, accent: FemhoAccent): FemhoColors = when (accent) {
    FemhoAccent.DEFAULT -> base
    FemhoAccent.MONOCOOL -> base.copy(
        dot1 = Color(0xFF8FC0FF),
        dot2 = Color(0xFF5A93F0),
        dot3 = Color(0xFF3B6FD6),
        kicker = Color(0xFF3B6FD6),
        onBrand = Color(0xFFFFFFFF),
        plouBlue = Color(0xFF8FC0FF),
        plouOrange = Color(0xFF5A93F0),
        plouOrangeInk = Color(0xFF3B6FD6),
        plouPink = Color(0xFF3B6FD6),
        plouPinkInk = Color(0xFF2B53A8),
        ringRadar = Color(0xB396BEFF),
    )
    FemhoAccent.MONOWARM -> base.copy(
        dot1 = Color(0xFFFF9C4F),
        dot2 = Color(0xFFFF8C6D),
        dot3 = Color(0xFFFF7B8B),
        onBrand = Color(0xFFFFFFFF),
        plouBlue = Color(0xFFFF9C4F),
        plouBlueInk = Color(0xFFE0793A),
        plouOrange = Color(0xFFFF8C6D),
        plouOrangeInk = Color(0xFFDD6B58),
        plouPink = Color(0xFFFF7B8B),
        plouPinkInk = Color(0xFFD75F76),
        ringRadar = Color(0xB3FFAC96),
    )
    FemhoAccent.SOFT -> base.copy(
        dot1 = Color(0xFFA9C9FF),
        dot2 = Color(0xFFFFC79A),
        dot3 = Color(0xFFFFB1C8),
        onBrand = Color(0xFF14151A),
        plouBlue = Color(0xFFA9C9FF),
        plouOrange = Color(0xFFFFC79A),
        plouPink = Color(0xFFFFB1C8),
        ringRadar = Color(0xB3FFCDB4),
    )
}
